### ISSUE TITLE
Feature Request-  Badge Count Functionality

### ISSUE THREAD

**Issue by indiascope** [stfalcon-studio/BottomTabLayout#1]
Hi,

I found this library very good. i also use in my project. but i have to set badge count on tab. i go through library but not found any badge count related code.  you can implement badge count functionality ?

**Comment by bevzaanton** [comment]
Hi, @indiascope !
I have implemented badge count functionality.
Update BottomTabLayout version to 0.3

For showing bubble count on tabs.
```java
bottomTabLayout.showTabBubbleCount(R.id.menu_button1, 3);
```
You can style bubble with methods:
```java
bottomTabLayout.setTabBubbleColor(ContextCompat.getColor(this, R.color.blue));
bottomTabLayout.setTabBubblePadding(0, 0, 0, 0);
bottomTabLayout.setTabBubbleTextStyle(R.style.TextWhite12);
```

**Comment by indiascope** [comment]
Thanks for Great library. I implement this library in my project  and have to implement badge count functionality. you save my time. again thanks for your good work.

**Comment by bevzaanton** [comment]
Thank you for your kind words!
